spring:
  application:
    name: order-service
server:
  port: 8084

user-service:
  url: http://localhost:8083 # URL user-service
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: full
